/**
 * Registro de iconos de la UI: nombre de contenido (`IconName`) → componente
 * de Tabler. Un import explícito por icono para que solo se empaqueten estos.
 * Debe cubrir todos los nombres de `ICON_NAMES` (lo comprueba `satisfies`).
 */
import type { Component } from 'vue'
import {
  IconSoccerField,
  IconBuildingStadium,
  IconBlocks,
  IconWall,
  IconTexture,
  IconLayoutGrid,
  IconArmchair,
  IconBolt,
  IconUsers,
  IconHammer,
  IconArrowsMove,
  IconArrowBigUpLines,
  IconNotebook,
  IconBallFootball,
  IconStairs,
  IconPlayFootball,
  IconFlag,
  IconArchive,
  IconBath,
  IconToiletPaper,
  IconWashHand,
  IconArmchair2,
  IconDesk,
  IconChairDirector,
  IconFolder,
  IconTree,
  IconPlant,
  IconLamp,
  IconTrash,
  IconPicnicTable,
  IconFountain,
  IconSeedling,
  IconMassage,
  IconBarbell,
  IconStretching,
  IconCoffee,
  IconCup,
  IconShirtSport,
  IconBriefcase,
  IconTicket,
  IconFirstAidKit,
  IconPackage,
  IconCamera,
  IconDoor,
  IconFence,
  IconDroplet,
  IconBulb,
  IconLawnMower,
  IconShield,
  IconClipboard,
  IconDeviceCctv,
  IconLock,
  IconRotateClockwise,
} from '@tabler/icons-vue'
import type { IconName } from '@/content/icons'

export const ICON_COMPONENTS = {
  'soccer-field': IconSoccerField,
  'building-stadium': IconBuildingStadium,
  blocks: IconBlocks,
  wall: IconWall,
  texture: IconTexture,
  'layout-grid': IconLayoutGrid,
  armchair: IconArmchair,
  bolt: IconBolt,
  users: IconUsers,
  hammer: IconHammer,
  'arrows-move': IconArrowsMove,
  'arrow-big-up-lines': IconArrowBigUpLines,
  notebook: IconNotebook,
  'ball-football': IconBallFootball,
  stairs: IconStairs,
  'play-football': IconPlayFootball,
  flag: IconFlag,
  archive: IconArchive,
  bath: IconBath,
  'toilet-paper': IconToiletPaper,
  'wash-hand': IconWashHand,
  'armchair-2': IconArmchair2,
  desk: IconDesk,
  'chair-director': IconChairDirector,
  folder: IconFolder,
  tree: IconTree,
  plant: IconPlant,
  lamp: IconLamp,
  trash: IconTrash,
  'picnic-table': IconPicnicTable,
  fountain: IconFountain,
  seedling: IconSeedling,
  massage: IconMassage,
  barbell: IconBarbell,
  stretching: IconStretching,
  coffee: IconCoffee,
  cup: IconCup,
  'shirt-sport': IconShirtSport,
  briefcase: IconBriefcase,
  ticket: IconTicket,
  'first-aid-kit': IconFirstAidKit,
  package: IconPackage,
  camera: IconCamera,
  door: IconDoor,
  fence: IconFence,
  droplet: IconDroplet,
  bulb: IconBulb,
  'lawn-mower': IconLawnMower,
  shield: IconShield,
  clipboard: IconClipboard,
  'device-cctv': IconDeviceCctv,
  lock: IconLock,
  'rotate-clockwise': IconRotateClockwise,
} satisfies Record<IconName, Component>
